[package]
name = "ghostly"
version = "0.1.0"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]

[dependencies]
gfx_device_gl = "0.14.1"
piston-ai_behavior = "0.20.0"
piston_window = "0.66.0"
piston2d-sprite = "0.36.0"
find_folder = "0.3.0"
uuid = "0.1.17"
